name: taxonomist
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  
  # DL
  - pytorch
  - torchvision
  - pytorch-cuda
  - lightning
  - wandb
  - transformers
  - huggingface_hub
  - datasets
  - open-clip-torch
  - torchmetrics
  - onnx
  - onnxruntime
  - timm
  - albumentations
  - omegaconf
  - bigtree
  - pycocotools

  # DS
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - opencv
  - pillow>=6.0.0
  - numba
  - joblib
  - xarray

  # Plotting + viz
  - matplotlib
  - seaborn
  - bokeh
  - plotly
  - streamlit>=1.21
  - gradio
  - tensorboard

  # ipython + notebooks
  - ipython
  - notebook
  - jupyterlab
  - ipywidgets
  - ipykernel

  # Others
  - tqdm
  - pytest
  - ruff
  - openpyxl

  - pip
