[project]
name = "taxonomist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "albumentations>=2.0.4",
    "datasets>=3.3.2",
    "joblib>=1.4.2",
    "lightning>=2.5.0.post0",
    "numpy>=2.0.2",
    "omegaconf>=2.3.0",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "timm>=1.0.15",
    "tqdm>=4.67.1",
    "wandb>=0.19.7",
]

[project.scripts]
taxonomist = "taxonomist.cli:main"

[tool.uv]
package = true

[dependency-groups]
segment = [
    "opencv-python>=4.11.0.86",
    "pycocotools>=2.0.8",
    "scikit-image>=0.24.0",
]
